---
title: "mp3"
author: "Cathy Lee, Lizette Carpenter, Ha Cao"
date: "7 April 2018"
output: html_document
---

```{r message = FALSE}
# load the libraries and data
devtools::install_github("beanumber/macleish")
library(tidyverse)
library(sf)
library(macleish)
library(leaflet)
packageVersion("macleish")
```

```{r}
# explore the data
names(macleish_layers)
# trails is existing trails shapefile
# forests is vegetation type shapefile
# streams and wetlands are hydrology shapefile
# challenge_courses is challenge course element locations shapefile
# boundary is property boundary shapefile
```

```{r}
trails <- macleish_layers[["trails"]] %>%
  mutate(computed_length = st_length(geometry))
```

```{r}
# group trails with the same name
trails_combined <- trails %>%
  group_by(name) %>%
  summarize(color = first(color),
            length = sum(computed_length))
```

```{r}
# join the two sf data frames
trails_intersect <- st_intersection(trails_combined,
                macleish_layers[["contours_3m"]]) %>%
  st_cast("POINT") 
# ELEV_M is elevation above or below sea level, in meters
```

```{r}
primitive_plot <- leaflet() %>%
  addTiles() %>%
  addPolylines(data = trails_combined, weight = 1, color = "black") %>%
  addPolylines(data = macleish_layers[["contours_3m"]], weight = 1, color = "red")
primitive_plot 
```

```{r}
# summarize to see for each trail, how many times it changes its elevation, what is the highest/lowest contour, and what is the mean change in height
trails_change_Elevation <- trails_intersect %>%
  group_by(name) %>%
  summarize(num_change = n(),
            min_height = min(ELEV_M),
            max_height = max(ELEV_M)) %>%
  mutate(mean_change = (max_height - min_height)/num_change)
```

```{r}
# join trails_change_Elevation back to trails_intersect
trails_intersect <- st_join(trails_intersect, trails_change_Elevation)
```

```{r}
# find if any trails intersect any streams
trails_intersect_streams <- st_intersection(trails_combined,
                macleish_layers[["streams"]]) 
```





